#!/usr/bin/env ruby

git_bundles = [
  'git://github.com/scrooloose/nerdcommenter.git',
  'git://github.com/scrooloose/nerdtree.git',
  'git://github.com/msanders/snipmate.vim.git',
  'git://github.com/scrooloose/syntastic.git',
  'git://github.com/tpope/vim-cucumber.git',
  'git://github.com/tpope/vim-endwise.git',
  'git://github.com/tpope/vim-git.git',
  'git://github.com/tpope/vim-haml.git',
  'git://github.com/tpope/vim-rails.git',
  'git://github.com/tpope/vim-surround.git',
  'git://github.com/mattn/gist-vim.git',

  'git://github.com/DexterTheDragon/vim-rest.git',
  "git://github.com/tsaleh/vim-supertab.git",
  # "git://github.com/tsaleh/vim-align.git",



  # "git://github.com/astashov/vim-ruby-debugger.git",
  # "git://github.com/timcharper/textile.vim.git",
  # "git://github.com/tpope/vim-fugitive.git",
  # "git://github.com/tpope/vim-markdown.git",
  # "git://github.com/tpope/vim-repeat.git",
  # "git://github.com/tpope/vim-vividchalk.git",
  # "git://github.com/tsaleh/vim-shoulda.git",
  # "git://github.com/tsaleh/vim-tcomment.git",
  # "git://github.com/vim-ruby/vim-ruby.git",
]

vim_org_scripts = [
  ['matchit', '8196', 'zip'],
  ['taglist', '7701', 'zip'],
  ['yankring', '12258', 'zip'],
  ['SearchComplete', '1388', 'plugin'],
  # ['SuperTab', '11853', 'vba'],
  ['php', '8651', 'tar.gz'],
  ['pydoc', '13092', 'plugin'],
  ['searchfold', '9850', 'plugin'],
  ['tasklist', '10388', 'plugin'],
  #
  # ["IndexedSearch", "7062",  "plugin"],
  # ["gist",          "12732", "plugin"],
  # ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

pathogen_f_path = File.join(File.dirname(__FILE__), 'autoload/pathogen.vim')
unless File.exist?(pathogen_f_path)
    FileUtils.mkdir_p(File.dirname(pathogen_f_path))
    File.open(pathogen_f_path, 'w') {|f| f << open('http://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim').read}
end

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.mkdir_p(bundles_dir) unless File.exist?(bundles_dir)
FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  ext = ['tar.gz','zip'].include?(script_type) ? script_type : 'vim'
  local_file = File.join(name, script_type, "#{name}.#{ext}")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    %x(unzip -d #{name} #{local_file})
    FileUtils.rm_rf(File.dirname(local_file))
  end
  if script_type == 'tar.gz'
    %x(tar xfv #{local_file} -C #{name})
    FileUtils.rm_rf(File.dirname(local_file))
  end
end
